[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput --clear"]

[start]
cmd = "gunicorn mobile_inventory.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
